language: go

go: 1.12.x
go_import_path: github.com/src-d/gitcollector

matrix:
  fast_finish: true

services:
  - docker

script:
  - GO111MODULE=on
  - make ci-script

jobs:
  include:
    - os: linux
      sudo: required
      dist: xenial

      before_deploy:
      - make packages

      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*linux_amd64.tar.gz
        skip_cleanup: true
        on:
          tags: true
      
      after_deploy:
        - make docker-push-latest-release

    - os: osx
      osx_image: xcode10.2

      before_deploy:
      - make packages

      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*darwin_amd64.tar.gz
        skip_cleanup: true
        on:
          tags: true
